ticker_interval: 5
news_interval: 5
reaction_percent: 2.0

db_scheme: tickers_scheme.sql
# Database for testing
db_test: qbot_test
# Data for testing db
db_test_data: test_tickers.sql
# Default password for postgres role, if required
db_defpass: '12345'
# Main connection params
postgresql:
  host: localhost
  port: 5432
  database: qbot
  user: qbot
  password: qbot
# Ticker mapping for ticker <> RBC tag
exceptions:
  EUR_RUB__TOM: eur-usd